### ISSUE TITLE
Building main.hex

### ISSUE THREAD

**Issue by rmnlsn** [OpenSource-EBike-firmware/TSDZ2_wiki#11]
Great Team,

congratulation for your firmware project for TSDZ2!

Can you help me to clarify a build step from the source code?
How can i convert the main.ihx to obtain the main.hex to verify if the checksum of main.hex is the same of your TSDZ2-vxxx.hex?

Thanks for your work,
Alessandro

**Comment by casainho** [comment]
Are you on Linux?

**Comment by rmnlsn** [comment]
No, I'm on Windows 10.

**Comment by casainho** [comment]
I can only help if you are non Linux. Maybe other developers can help you.

**Comment by rmnlsn** [comment]
Ok. THX. Can you confirm that the checksum of the main.hex and the TSDZ2-vxxx.hex should have the same checksum?
