### ISSUE TITLE
Non reversible temperature label for casa

### ISSUE THREAD

**Issue by sbridger** [OpenSource-EBike-firmware/TSDZ2_wiki#8]
Hi  Casainho

I had to get 10 of these  [over-temperature tell-tale stickers](https://nz.rs-online.com/web/p/temperature-sensitive-labels/7799772/) so I have several left over. You stick them on the motor.

Give me your address and I will post you one, if you would like it.

**Comment by casainho** [comment]
Thanks but I prefer to use the temperature sensor -- it is safer since it is automatically. I push a lot for my ebikes sometimes, when doing trails on mountains, so I do not have time to manage the temeprature manually. Also for ebikes of my family, it must be automatically.

**Comment by sbridger** [comment]
The sticker is a permanent (color-changing) indication of maximum temperature, to go on the motor itself (inside the crankcase - out of sight), as a diagnostic which is independent of firmware, and that can't be erased from eeprom during updates.

They aren't a replacement for the sensor in any way, just a very simple reliable way to know how hot it got (eg when the motor seems to have become "weak")

**Comment by casainho** [comment]
Ok thanks anyway. I am to busy to take advantage of them other way they would end on a pill of the things I have here that I do not touch because lack of time.

**Comment by sbridger** [comment]
I know the feeling. Offers open while I still have them.
